-- ============================================================
-- TABLES SUPABASE POUR YARID - CATEGORIES + AVIS
-- ============================================================

-- Table: categories
-- Gere les categories affichees sur la page d'accueil
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom TEXT NOT NULL,
    filtre TEXT NOT NULL,
    ordre INTEGER DEFAULT 0,
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Activer RLS
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- Politiques: lecture publique, ecriture admin (a adapter selon votre auth)
CREATE POLICY "categories_select_all" ON categories FOR SELECT USING (true);
CREATE POLICY "categories_insert_admin" ON categories FOR INSERT WITH CHECK (true);
CREATE POLICY "categories_update_admin" ON categories FOR UPDATE USING (true);
CREATE POLICY "categories_delete_admin" ON categories FOR DELETE USING (true);

-- Categories par defaut
INSERT INTO categories (nom, filtre, ordre, active) VALUES
    ('Tout', 'all', 0, true),
    ('Parfums', 'parfums', 1, true),
    ('Tech', 'tech', 2, true),
    ('Mode', 'mode', 3, true),
    ('Chaussures', 'chaussures', 4, true),
    ('Sacs', 'sacs', 5, true),
    ('Montres', 'montres', 6, true),
    ('Maison', 'maison', 7, true)
ON CONFLICT DO NOTHING;

-- ============================================================

-- Table: avis (reviews)
-- Stocke les avis clients avec notation et commentaires
CREATE TABLE IF NOT EXISTS avis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produit_id BIGINT NOT NULL REFERENCES PRODUITS(id) ON DELETE CASCADE,
    client_nom TEXT DEFAULT 'Client',
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    note INTEGER CHECK (note >= 1 AND note <= 5),
    comment TEXT DEFAULT '',
    commentaire TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index pour performance
CREATE INDEX IF NOT EXISTS idx_avis_produit_id ON avis(produit_id);
CREATE INDEX IF NOT EXISTS idx_avis_created_at ON avis(created_at DESC);

-- Activer RLS
ALTER TABLE avis ENABLE ROW LEVEL SECURITY;

-- Politiques
CREATE POLICY "avis_select_all" ON avis FOR SELECT USING (true);
CREATE POLICY "avis_insert_all" ON avis FOR INSERT WITH CHECK (true);
CREATE POLICY "avis_delete_admin" ON avis FOR DELETE USING (true);

-- ============================================================
-- VERIFICATION
-- ============================================================
-- SELECT * FROM categories ORDER BY ordre;
-- SELECT * FROM avis WHERE produit_id = 1 ORDER BY created_at DESC;
